### ISSUE TITLE
I've created Router within MiniDrawer

### ISSUE THREAD

**Issue by Henotis** [SuperArtisMickens/TTP8-NowWithPages#2]
I moved MiniDrawer to src since it contains everything. For now we can work within it and rename it later if we want. I added some comments to help you guys take note of what I've done in the "PageLinkStarter" branch.  The sidebar looks kinda janky now sadly.
* I moved some of the components to a new page
* I called the components from within those new pages
* I called the pages within <Switch> to make it display those pages with the components in them

**Comment by yauhofung** [comment]
The `npm start` command takes significantly longer to execute in the PageLinkStarter branch than the main branch. Perhaps we should consider optimizing run time before merging the pull request.

**Comment by yauhofung** [comment]
Issue closed: Branch has been merged with main.
